# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: evilmagics
          template: classic
          base: ''
          base_indepth: yes
          config_timezone: Asia/Jakarta
          config_display: columns
          optimize: css, xml
          use_prebuilt_image: yes

          # Plugin configuration
          plugin_lines: yes

          # Archivements plugin
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # Languages plugin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: programming, markup
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_other: yes
          plugin_languages_recent_categories: programming, markup
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Commit calendar plugin
          plugin_calendar: yes
          plugin_calendar_limit: 2

          extras_css: |
            .field svg {
              fill: #58b9d0;
            }
            .field {
              color: #2986b8;
            }
            h1, h2, h3 {
              color: #284a92 !important;
            }
          extras_js: |
            for (const {a, b} of [
              {a:"#216e39", b:"#b7dfcb"},
              {a:"#30a14e", b:"#58b9d0"},
              {a:"#40c463", b:"#2986b8"},
              {a:"#9be9a8", b:"#284a92"},
              {a:"#ebedf0", b:"#192062"},
            ])
            document.querySelectorAll(`svg g [fill="${a}"]`).forEach(node => node.setAttribute("fill", b))
